// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDiRsZzagUWNr4XVN74mGKMyoXErGqVVJM',
//     appId: '1:113892560442:web:949cc2205ff38875f42f03',
//     messagingSenderId: '113892560442',
//     projectId: 'gaduate-fc648',
//     authDomain: 'gaduate-fc648.firebaseapp.com',
//     storageBucket: 'gaduate-fc648.appspot.com',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBBIeWeixIc9_Ey6ceYRtozBUP6D3NHCbE',
//     appId: '1:113892560442:android:62e8e968d8d9e47bf42f03',
//     messagingSenderId: '113892560442',
//     projectId: 'gaduate-fc648',
//     storageBucket: 'gaduate-fc648.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyA_Ey5POmEkS7XkOtKK9N71jzhhqsjp5ik',
//     appId: '1:113892560442:ios:d89f2b92c4848816f42f03',
//     messagingSenderId: '113892560442',
//     projectId: 'gaduate-fc648',
//     storageBucket: 'gaduate-fc648.appspot.com',
//     iosBundleId: 'com.example.graduate',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyA_Ey5POmEkS7XkOtKK9N71jzhhqsjp5ik',
//     appId: '1:113892560442:ios:d89f2b92c4848816f42f03',
//     messagingSenderId: '113892560442',
//     projectId: 'gaduate-fc648',
//     storageBucket: 'gaduate-fc648.appspot.com',
//     iosBundleId: 'com.example.graduate',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyDiRsZzagUWNr4XVN74mGKMyoXErGqVVJM',
//     appId: '1:113892560442:web:0184dd6c591eb8d8f42f03',
//     messagingSenderId: '113892560442',
//     projectId: 'gaduate-fc648',
//     authDomain: 'gaduate-fc648.firebaseapp.com',
//     storageBucket: 'gaduate-fc648.appspot.com',
//   );
// }
